//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultInformation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicHistory
    {
        public int Id { get; set; }
        public Nullable<int> Percentage { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CombinationId { get; set; }
        public Nullable<int> AwardingBodyId { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public Nullable<int> AcademicLevelId { get; set; }
    
        public virtual AcademicLevel AcademicLevel { get; set; }
        public virtual AwardingBody AwardingBody { get; set; }
        public virtual Combination Combination { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual Student Student { get; set; }
    }
}
