//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultInformation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Acro { get; set; }
        public int CreditHours { get; set; }
        public decimal LabCredits { get; set; }
        public string Code { get; set; }
        public byte[] CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
