//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultInformation.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIMSEntities : DbContext
    {
        public SIMSEntities()
            : base("name=SIMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<AcademicHistory> AcademicHistories { get; set; }
        public virtual DbSet<AcademicLevel> AcademicLevels { get; set; }
        public virtual DbSet<AcademicSession> AcademicSessions { get; set; }
        public virtual DbSet<AwardingBody> AwardingBodies { get; set; }
        public virtual DbSet<Combination> Combinations { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Institute> Institutes { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
    }
}
