//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultInformation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Registrations = new HashSet<Registration>();
            this.AcademicHistories = new HashSet<AcademicHistory>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SystemId { get; set; }
        public string RollNo { get; set; }
        public string ResistrationNo { get; set; }
        public string CNIC { get; set; }
        public string FatherFirstName { get; set; }
        public string FatherMiddleName { get; set; }
        public string FatherLastName { get; set; }
        public string FatherCNIC { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> SemesterId { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
        public virtual ICollection<AcademicHistory> AcademicHistories { get; set; }
        public virtual Program Program { get; set; }
    }
}
