//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultInformation.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Http;
    using System.Web.Http.OData;

    public partial class PersonModel //: SingleResult<DAL.Person>
    {
        public PersonModel()
        {

        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string SystemId { get; set; }
        public string RollNo { get; set; }
        public string ResistrationNo { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> FatherId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }

        /*  */
    }
}
