//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultInformation.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Http;
    using System.Web.Http.OData;

    public  class AcademicHistoryModel //: SingleResult<DAL.Person>
    {
        public AcademicHistoryModel()
        {

        }

        public int Id { get; set; }
        public Nullable<int> Percentage { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CombinationId { get; set; }
        public Nullable<int> AwardingBodyId { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public Nullable<int> AcademicLevelId { get; set; }

        public string AcademicLevel  { get; set; }
        public string AwardingBody  { get; set; }
        public string Combination  { get; set; }
        public string Institute  { get; set; }
        public string Student { get; set; }
        /*  */
    }
}
