//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultInformation.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Http;
    using System.Web.Http.OData;

    public class CourseModel //: SingleResult<DAL.Student>
    {
        public CourseModel()
        {

        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Acro { get; set; }
        public int CreditHours { get; set; }
        public decimal LabCredits { get; set; }
        public string Code { get; set; }
       
        /*  */
    }
}
